name: Sort Trojan Accounts

on:
  workflow_dispatch:

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install websocket-client requests

      - name: Run sorting script
        run: |
          python check_trojan_sort.py

      - name: Commit results
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add results/sorted_accounts.txt
          git commit -m "Update sorted accounts"
          git push
