name: Trojan Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # jalan otomatis tiap 6 jam

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests websocket-client

      - name: Run Trojan Checker
        run: |
          python check_trojan_sort.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/sni.txt
          git commit -m "Update hasil cek Trojan TLS aktif" || echo "No changes to commit"
          git push
