name: Sort Trojan WS

# Bisa dijalankan manual via "Run workflow"
on:
  workflow_dispatch:

jobs:
  sort-trojan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Trojan WS Sorter
      run: |
        python check_trojan_runner.py

    - name: Upload output.txt as artifact
      uses: actions/upload-artifact@v3
      with:
        name: trojan-output
        path: output.txt
