name: Sort & Test Trojan Accounts

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  sort-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --quiet requests speedtest-cli

      - name: Run Trojan sorter & speedtest
        run: |
          python check_trojan_runner.py \
            --input input.txt \
            --sorted sorted.txt \
            --active active.txt \
            --only-ws \
            --require-sni-host \
            --delay 1 \
            --timeout 10 || true

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sorted.txt active.txt
          git commit -m "update: sorted & active trojan accounts with speedtest" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
