name: Trojan Check V2Ray

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install V2Ray CLI
        run: |
          curl -L https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip -o v2ray.zip
          unzip v2ray.zip -d v2ray
          chmod +x v2ray/v2ray

      - name: Run Trojan Check
        run: |
          mkdir -p results
          python3 check_trojan_v2ray.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/sni.txt
          git commit -m "Update hasil cek Trojan TLS aktif via V2Ray" || echo "No changes"
          git push
