name: Check Trojan Accounts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # jalan tiap 6 jam

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: |
          pip install requests

      - name: Install Ookla Speedtest CLI
        run: |
          if [ ! -f ./speedtest ]; then
            echo "⚡ Installing Ookla Speedtest CLI..."
            curl -L -o speedtest.tgz https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
            tar -xvzf speedtest.tgz
            mv speedtest ./speedtest
            chmod +x ./speedtest
          else
            echo "✅ Speedtest CLI already installed, skipping..."
          fi

      - name: Run Trojan checker
        run: |
          python check_trojan_runner.py \
            --input accounts.txt \
            --sorted sorted.txt \
            --active active.txt \
            --speedtest ./speedtest

      - name: Commit & push results
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.txt"
          message: "update: sorted & active Trojan accounts"
          default_author: github_actions
