name: Trojan Check V2Ray

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests websocket-client

      - name: Run Trojan Checker
        run: |
          mkdir -p results
          python3 check_trojan_runner.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/sni.txt results/log.txt
          git commit -m "Update hasil cek Trojan TLS/WS sederhana" || echo "No changes"
          git push
