name: Sort WS Trojan Accounts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sort_ws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Jalankan sort WS accounts
        run: |
          mkdir -p results
          python3 check_trojan_runner.py

      - name: Commit hasil sortir
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add results/sorted.txt
          git commit -m "Update hasil sortir akun WS" || echo "No changes"
          git push
