name: Sort & Check Trojan Accounts

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  sort:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --quiet requests speedtest-cli

      - name: Run Trojan sorter & speedtest
        run: |
          python check_trojan_runner.py \
            --input input.txt \
            --sorted sorted.txt \
            --active active.txt \
            --only-ws \
            --require-sni-host \
            --delay 1 \
            --timeout 10 || true

      - name: Commit sorted & active output
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update sorted.txt & active.txt (generated by workflow)"
          add: 'sorted.txt,active.txt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
