name: Test Trojan Accounts

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # setiap hari jam 00:00 UTC

jobs:
  test-accounts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install requests
      run: pip install requests

    - name: Run Trojan test
      run: python tester.py

    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add active.txt dead.txt
        git commit -m "Update test results" || echo "No changes"
        git push
